# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: false # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Yuri Gomes
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Fullstack Developer, graduando em Análise e Desenvolvimento de Sistemas. Atualmente estudando tecnologias baseadas em Javascript (NodeJS, MongoDB, Express, AngularJS e React). Bom entusiasta de novas tecnologias e disposto a trabalhar em grandes equipes!'

#sidebar links
email: yuurig@gmail.com
website: github.com/met4tron #do not add http://
linkedin: yuurig
github: met4tron
twitter: '@Haddouken__'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
